branch-defaults:
  default:
    environment: jece-env
  develop:
    environment: jece-env
global:
  application_name: jeceProject
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-1
  sc: git
