branch-defaults:
  default:
    environment: jece-env
global:
  application_name: jece
  default_ec2_keyname: null
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  sc: git
