# Generated by Django 5.2.6 on 2025-10-18 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('fees', models.PositiveIntegerField(default=0, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['course_title'],
                'indexes': [models.Index(fields=['-created_at'], name='courses_cou_created_c141ec_idx')],
                'unique_together': {('course_title', 'university')},
            },
        ),
    ]
