# Generated by Django 5.2.6 on 2025-10-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_fees'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
