# Generated by Django 5.2.6 on 2025-10-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_alter_course_course_title_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_title_university',
        ),
    ]
